### ISSUE TITLE
Proof of Possession: "certain attacks"

### ISSUE THREAD

**Issue by thomwiggers** [lamps-wg/cmp-updates#10]
>[4.3. ](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html#section-4.3)[Proof-of-Possession (POP) of Private Key](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html#name-proof-of-possession-pop-of-)
> In order to prevent _certain attacks_ [...]

(emphasis mine)

We've had quite a bit of discussion about "certain attacks" on the mailing list. The remainder of the text hints a bit at attacks in deployments where the binding between the end entity and the key isn't rigorously checked, but does it make sense to e.g. refer to [Appendix A of this paper](https://s3.amazonaws.com/files.douglas.stebila.ca/files/research/papers/CCS-GHLOSZ22.pdf) which makes a little bit more of an overview?

(This comment comes from my academic writing background, so leaving this or other references out for editorial reasons is perfectly fine)

**Comment by ounsworth** [comment]
Oh hey, I wrote Appendix A. 
+1 to this suggestion!

**Comment by HBrock** [comment]
@ounsworth do you want to add a security consideration briefly describing the risk/attack a POP addresses bases on Appendix A of that paper?

**Comment by HBrock** [comment]
Authors meeting 2.3.23:
Mike will provide a summary as security consideration.

**Comment by HBrock** [comment]
concluded with Mike's PR
