### ISSUE TITLE
4.3.4 PoP of KEM keys: mention encaps/decaps?

### ISSUE THREAD

**Issue by thomwiggers** [lamps-wg/cmp-updates#11]
> [4.3.4. ](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html#section-4.3.4)[Key Encapsulation Mechanism Keys](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html#name-key-encapsulation-mechanism)

> [...]
> The indirect method is to issue a certificate that is encrypted for the end entity (and have the end entity demonstrate its ability to decrypt this certificate in the confirmation message). This allows a CA to issue a certificate in a form that can only be used by the intended end entity.

I'm nitpicking a bit, but perhaps it makes sense to clarify that we encrypt the certificate using a shared key encapsulated to the private key, and that the ciphertext needs to be provided along the certificate as well.

For example:

> The indirect method is to issue a certificate that is encrypted for the end entity using a shared secret key encapsulated to the private key (and have the end entity demonstrate its ability to decapsulate the shared secret key from the ciphertext and decrypt this certificate in the confirmation message). This allows a CA to issue a certificate in a form that can only be used by the intended end entity.

A bit verbose, perhaps, but it may help clarify that the KEM mechanism does differ from the encryption key mechanism in this important way.

**Comment by HBrock** [comment]
Thank you for this proposal.
When using the indirect method, the encrypted certificate is provided using EnvelopedData. This implies providing an encrypted content encryption key. But certainly it is good to explicitly state usage of encyps/decaps here.
Finally it is even more complex as the shared secret key is derived from the encypsulated key using a KDF :-)

`The indirect method is to issue a certificate that is encrypted for the end entity using a shared secret key derived from a key encapsulated using its public key (and have the end entity demonstrate its ability to use its private key for decapsulation of the KEM ciphertext, derive the shared secret key, decrypt this certificate, and provide a hash of the certificate in the confirmation message).  This allows a CA to issue a certificate in a form that can only be used by the intended end entity.`

**Comment by ounsworth** [comment]
Meeting 2023-3-2:
You could borrow the KEM definition from either
https://datatracker.ietf.org/doc/html/draft-ietf-tls-hybrid-design#name-key-encapsulation-mechanism

or 

https://datatracker.ietf.org/doc/draft-ietf-lamps-cms-kemri/
section 1

**Comment by HBrock** [comment]
Adding `Note: A definition of Key Encapsulation Mechanisms can be found in {{I-D.ietf-cms-kemri, Section 1}}.`
