### ISSUE TITLE
Appendix B would needs a review

### ISSUE THREAD

**Issue by HBrock** [lamps-wg/cmp-updates#18]
ToDo: Review Appendix B and try to push the content to Section 4 or Section 5 of this document.
ToDo: Possibly add support for certificates containing KEM keys.

**Comment by HBrock** [comment]
Meeting 3.2.23:
Address after IETF116

**Comment by DDvO** [comment]
Looks like this is due meanwhile.
Who should ideally review this?

**Comment by HBrock** [comment]
Updated Appendix B with fa57a14f292affa3a60be051cc7c1eb318320aff
