### ISSUE TITLE
Replace the ASN.1 version 1988 module from Appendix F with the 2002 version module

### ISSUE THREAD

**Issue by HBrock** [lamps-wg/cmp-updates#40]
Should we remove the ASN.1 version 1988 module completely from the document and replace it with the version 2002 module in Appendix F?
Then there is no complete ASN.1 version 1988 module available containing the KEM support.

**Comment by HBrock** [comment]
@johngray-dev will have a look into

**Comment by johngray-dev** [comment]
Yes, I think we should replace the 1988 module and replace with 2002.   I also noticed our ASN.1 module has a typo in it:

  cmp2012(3) },

It says cmp2012 instead of cmp2021(3).

**Comment by johngray-dev** [comment]
I fixed the typo...     Will look at how easy it will be to rip out the 1988 module.

**Comment by HBrock** [comment]
> Yes, I think we should replace the 1988 module and replace with 2002. I also noticed our ASN.1 module has a typo in it:
> 
> cmp2012(3) },
> 
> It says cmp2012 instead of cmp2021(3).

Thank you for spotting this. 
Sadly, this typo is also present in RFC9480 Appendix A.2. In Appendix A.1 it is correct.

**Comment by HBrock** [comment]
summary of meeting 26.02.2024:
@johngray-dev will report the errata
We decided to drop the 1988 syntax ASN.1 module.
