### ISSUE TITLE
Move all of section 5.1.3.4 into section 5.1.3.1 ?

### ISSUE THREAD

**Issue by DDvO** [lamps-wg/cmp-updates#7]
[this issue was carved out of #3]

The HPKE+MAC-based message protection is 'just' another special case of the MAC-based message protection very briefly described in section 5.1.3.1. So IMO all the text of 5.1.3.4 should better move there (strictly speaking, as a subsection of 5.1.3.1, but I'd say we can and should save the extra nesting).

**Comment by HBrock** [comment]
Currently Section 5.1.3 is structured based on the keys to use for message protection. Here we use KEM keys for message protection and only use a symmetric key indirectly, like with Diffie-Hellmann in Section 5.1.3.2. I would propose to rename Section 5.1.3.1 to focus it more on pre-shared keys and passwords and keep the protection using KEM keys in Section 5.1.3.4.

**Comment by DDvO** [comment]
Sounds good to me.

**Comment by HBrock** [comment]
Resolved with https://github.com/lamps-wg/cmp-updates/commit/92bacd31fa196e317930b6e2197c3f3673dd75bd
